name: init
on:
  create:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Step 1
      run: echo "New repo created"
    # - name: Step 2
    #   run: npm i -g kaskadi-cli
