name: testing
on: [push]
jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: npm i
    - uses: paambaati/codeclimate-action@master
      env:
        CC_TEST_REPORTER_ID: 7b14f1f9497bb8e48bbd7efbe19c985f33ddc452ac0a5931699136a43494c6ee
      with:
        coverageCommand: npm test
